### ISSUE TITLE
Cannot quit VLC on OSX

### ISSUE THREAD

**Issue by roelvan** [XaF/TraktForVLC#100]
Using the latest TraktForVLC version I cannot quit VLC without killing it using the task manager. Running VLC -vv shows me that this process keeps running: `lua interface: The Dark Knight (2008) is playing! :)`. Every second I still see [trakt] logs.

When I uninstall TraktForVLC VLC works normally again.

**Comment by roelvan** [comment]
Completely re-installing VLC did the trick! Maybe a conflict with the old version of TraktVLC?
![04-26-2018-11 29 00](https://user-images.githubusercontent.com/2583837/39285906-249b3c18-4945-11e8-8e07-242f6d86f4fb.jpg)

**Comment by XaF** [comment]
I implemented a simple trick to insure that `TraktForVLC` checks for VLC status (by querying the current volume). However, I find that weird it happened as VLC should shut down all lua scripts and not keep them busy. Anyway, the patch should be implemented in a soon-to-be latest release (when tests are passing).

**Comment by roelvan** [comment]
@XaF still having issues: quitting while the video is playing won't work. First pause and then quit = 👍

**Comment by XaF** [comment]
Hm. I don't see any reason why it would work while paused and not while playing, as the internal loop is doing the same thing in both cases. What VLC version are you using? I'm unable to reproduce your issue.. :(
