### ISSUE TITLE
OSX - Scrobbling not working

### ISSUE THREAD

**Issue by roelvan** [XaF/TraktForVLC#96]
Logs:
```
[trakt] lua interface error: (call_helper) Command: "/Users/roel/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "--quiet" "resolve" "--meta" "{\"filename\":\"Batman.The.Dark.Knight.2008.1080p.BluRay.x264.YIFY.mp4\"}" "--duration" "9133.481666" "--hash" "8b37bd9eb48dd8e9" "--size" "1828285704" 2>&1
[0000000100445ac8] [trakt] lua interface error: (call_helper) Unable to parse json
[0000000100445ac8] [trakt] lua interface error: (call_helper) Command output: 2018-04-20 11:43:24,091::ERROR::max() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 822, in run
  File "helper/commands/resolve.py", line 546, in search_hash
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 91, in <module>
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 822, in run
  File "helper/commands/resolve.py", line 546, in search_hash
ValueError: max() arg is an empty sequence
[43285] Failed to execute script trakt_helper
```

**Comment by roelvan** [comment]
```
[trakt] lua interface debug: (call_helper) Executing command: "/Users/roel/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "--quiet" "resolve" "--meta" "{\"filename\":\"Batman.The.Dark.Knight.2008.1080p.BluRay.x264.YIFY.mp4\"}" "--duration" "9133.481666" "--hash" "8b37bd9eb48dd8e9" "--size" "1828285704"
[0000000100445ac8] [trakt] lua interface debug: (call_helper) Received response: 2018-04-20 11:43:28,087::ERROR::max() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 822, in run
  File "helper/commands/resolve.py", line 546, in search_hash
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 91, in <module>
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 822, in run
  File "helper/commands/resolve.py", line 546, in search_hash
ValueError: max() arg is an empty sequence
[43295] Failed to execute script trakt_helper
```

**Comment by XaF** [comment]
Good catch! Thank you for the report. I merged the fix, the latest build should be made available with it soon!

**Comment by roelvan** [comment]
Yep that works, thanks:
```
[trakt] lua interface: The Dark Knight (2008) is playing! :) (0.000063/9133.481666)
[000000010051b088] [trakt] lua interface debug: Timers ran: {
	["@trakt.lua:2540"] = false,
	["@trakt.lua:1521"] = false,
	["@trakt.lua:2299"] = false,
}
```
```
[000000010051b088] [trakt] lua interface debug: (call_helper) Executing command: "/Users/roel/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "date" "--format" "%s.%f"
[000000010051b088] [trakt] lua interface debug: (call_helper) Received response: {
    "date": "1524185522.658766",
    "format": "%s.%f",
    "timezone": "UTC"
}
```
But I still don't see it on my Trakt profile. No red error logs either.

**Comment by roelvan** [comment]
Also I cannot Quit VLC anymore without killing it with the task manager.

**Comment by XaF** [comment]
For the "nothing on trakt.tv part", please see #98.
For the second one, please open another issue and give details of what's happening, including VLC logs.
